//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.default_Grab;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean PlayOrPause
        {
            get
            {
                return SteamVR_Actions.default_PlayOrPause;
            }
        }
        
        public virtual SteamVR_Action_Boolean SkipBack
        {
            get
            {
                return SteamVR_Actions.default_SkipBack;
            }
        }
        
        public virtual SteamVR_Action_Boolean SkipForward
        {
            get
            {
                return SteamVR_Actions.default_SkipForward;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToStart
        {
            get
            {
                return SteamVR_Actions.default_ToStart;
            }
        }
        
        public virtual SteamVR_Action_Boolean ClickLaser
        {
            get
            {
                return SteamVR_Actions.default_ClickLaser;
            }
        }
        
        public virtual SteamVR_Action_Boolean SpeedUp
        {
            get
            {
                return SteamVR_Actions.default_SpeedUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean SpeedDown
        {
            get
            {
                return SteamVR_Actions.default_SpeedDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean ResetCell
        {
            get
            {
                return SteamVR_Actions.default_ResetCell;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwapLaserColour
        {
            get
            {
                return SteamVR_Actions.default_SwapLaserColour;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwapColourMode
        {
            get
            {
                return SteamVR_Actions.default_SwapColourMode;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ChangePointerSize
        {
            get
            {
                return SteamVR_Actions.default_ChangePointerSize;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
